import React, { useEffect, useState } from 'react';
import { complaintApi } from '../services/api';

const labels: Record<string, { label: string; color: string }> = {
  OPEN: { label: 'Open / unassigned', color: 'bg-slate-500' }, UNASSIGNED: { label: 'Open / unassigned', color: 'bg-slate-500' }, ASSIGNED: { label: 'Assigned', color: 'bg-cyan-600' }, IN_PROGRESS: { label: 'Work in progress', color: 'bg-blue-600' }, VERIFIED_RESOLVED: { label: 'Resolved', color: 'bg-green-600' }, PARTIALLY_RESOLVED: { label: 'Partially resolved', color: 'bg-orange-500' }, NOT_RESOLVED: { label: 'Not resolved', color: 'bg-red-600' }, INSUFFICIENT_EVIDENCE: { label: 'Evidence issue', color: 'bg-purple-600' },
};

const Analytics: React.FC = () => {
  const [complaints, setComplaints] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { complaintApi.list().then(setComplaints).finally(() => setLoading(false)); }, []);
  const counts = complaints.reduce((all, item) => ({ ...all, [item.status]: (all[item.status] || 0) + 1 }), {} as Record<string, number>);
  const issueCounts = complaints.reduce((all, item) => ({ ...all, [item.issue_type]: (all[item.issue_type] || 0) + 1 }), {} as Record<string, number>);
  const total = complaints.length || 1;
  return <div className="max-w-6xl mx-auto space-y-8"><header><h1 className="text-3xl font-bold text-slate-900">MCC analytics</h1><p className="mt-1 text-slate-500">Live operational overview from complaints and final AI score categories.</p></header>{loading ? <p className="text-slate-500">Loading live analytics…</p> : <><section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{Object.entries(labels).filter(([status]) => status !== 'UNASSIGNED').map(([status, meta]) => <article key={status} className="bg-white border rounded-xl p-5"><p className="text-sm text-slate-500">{meta.label}</p><p className="mt-1 text-3xl font-bold">{counts[status] || 0}</p><div className="mt-3 h-2 rounded bg-slate-100 overflow-hidden"><div className={`${meta.color} h-full`} style={{ width: `${((counts[status] || 0) / total) * 100}%` }}/></div></article>)}</section><section className="grid lg:grid-cols-2 gap-6"><article className="bg-white border rounded-xl p-6"><h2 className="font-bold text-lg">Issue categories</h2><div className="mt-5 space-y-4">{Object.entries(issueCounts).map(([issue, count]: any) => <div key={issue}><div className="flex justify-between text-sm"><span className="capitalize">{issue.replace(/_/g, ' ')}</span><b>{count}</b></div><div className="mt-1 h-3 bg-slate-100 rounded overflow-hidden"><div className="h-full bg-blue-600" style={{ width: `${(count / total) * 100}%` }}/></div></div>)}{!complaints.length && <p className="text-slate-500">No live complaints yet.</p>}</div></article><article className="bg-white border rounded-xl p-6"><h2 className="font-bold text-lg">How to use this page</h2><ul className="mt-4 space-y-3 text-slate-600 text-sm"><li>• Track open and assigned workload.</li><li>• See final AI outcomes: resolved, partial, not resolved, or evidence issue.</li><li>• Identify the most frequently reported civic issue categories.</li><li>• Return to the map to see where those status markers are located.</li></ul></article></section></>}</div>;
};
export default Analytics;
