import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Image as ImageIcon, Zap } from 'lucide-react';
import { complaintApi, evidenceUrl } from '../services/api';
import ComparisonMetrics from '../components/ComparisonMetrics';
import { Complaint, Evidence } from '../types/complaint';

const ComplaintDetail: React.FC = () => {
  const { id } = useParams(); const [complaint, setComplaint] = useState<Complaint | null>(null); const [evidence, setEvidence] = useState<Evidence[]>([]); const [comparison, setComparison] = useState<any>(null); const [file, setFile] = useState<File | null>(null); const [type, setType] = useState<'BEFORE'|'AFTER'>('BEFORE'); const [busy, setBusy] = useState(false);
  const load = async () => { if (!id) return; const [current, items] = await Promise.all([complaintApi.get(+id), complaintApi.getEvidence(+id)]); setComplaint(current); setEvidence(items); try { setComparison(await complaintApi.getComparison(+id)); } catch { setComparison(null); } };
  useEffect(() => { void load(); }, [id]);
  const upload = async () => { if (!id || !file) return; setBusy(true); try { await complaintApi.uploadEvidence(+id, file, { type, timestamp: new Date().toISOString(), latitude: complaint?.latitude, longitude: complaint?.longitude }); setFile(null); await load(); } finally { setBusy(false); } };
  const verify = async () => { if (!id) return; setBusy(true); try { setComparison(await complaintApi.verify(+id)); await load(); } catch (error: any) { alert(error.response?.data?.detail || 'AI analysis failed'); } finally { setBusy(false); } };
  if (!complaint) return <div className="p-8 text-center">Loading complaint…</div>;
  const beforeItems = evidence.filter(item => item.type === 'BEFORE'); const afterItems = evidence.filter(item => item.type === 'AFTER'); const before = beforeItems[beforeItems.length - 1]; const after = afterItems[afterItems.length - 1];
  return <div className="max-w-5xl mx-auto space-y-6"><Link to="/complaints" className="text-blue-600 text-sm">← Back to complaints</Link><header><h1 className="text-3xl font-bold">{complaint.complaint_number}</h1><p className="mt-1 capitalize text-slate-600">{complaint.issue_type.replace('_', ' ')} · {complaint.address}</p></header><div className="grid lg:grid-cols-3 gap-6"><section className="bg-white border rounded-xl p-5 space-y-3"><h2 className="font-bold">Evidence</h2><select className="w-full border rounded p-2" value={type} onChange={event => setType(event.target.value as 'BEFORE'|'AFTER')}><option value="BEFORE">Before photo</option><option value="AFTER">After photo</option></select><input type="file" accept="image/*" onChange={event => setFile(event.target.files?.[0] || null)}/><button disabled={!file || busy} onClick={upload} className="w-full bg-blue-600 text-white p-2 rounded font-bold disabled:opacity-50">Upload photo</button><button disabled={!before || !after || busy} onClick={verify} className="w-full bg-slate-900 text-white p-3 rounded font-bold disabled:opacity-50 flex justify-center gap-2"><Zap className="w-5 h-5"/> {busy ? 'Analysing…' : 'Run final AI assessment'}</button><p className="text-xs text-slate-500">The AI score and category are final. No human decision is required.</p></section><section className="lg:col-span-2 bg-white border rounded-xl p-5"><h2 className="font-bold flex gap-2"><ImageIcon className="w-5 h-5"/> Before and After</h2><div className="grid sm:grid-cols-2 gap-4 mt-4">{[{label:'Before', item:before},{label:'After', item:after}].map(({label,item}) => <div key={label} className="border rounded overflow-hidden"><div className="p-2 text-sm font-bold">{label}</div>{item ? <img src={evidenceUrl(item.file_path)} alt={label} className="w-full aspect-video object-cover"/> : <p className="p-6 text-sm text-slate-500">Not uploaded.</p>}</div>)}</div></section></div><section className="bg-white border rounded-xl p-6"><h2 className="font-bold text-lg">Final AI result</h2>{comparison ? <div className="mt-4"><ComparisonMetrics result={comparison.result} explanation={comparison.explanation} evidenceScore={comparison.overall_evidence_score} metrics={{before_area:0,after_area:0,reduction_percent:0}}/></div> : <p className="mt-3 text-slate-500">Upload both photos and run AI assessment.</p>}</section></div>;
};
export default ComplaintDetail;
