import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { LayoutDashboard, CheckCircle, AlertCircle, Clock, TrendingUp, Map as MapIcon } from 'lucide-react';
import MysuruMap from '../components/MysuruMap';
import { complaintApi } from '../services/api';

const StatCard = ({ title, value, icon: Icon, color }: { title: string, value: number, icon: any, color: string }) => <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 flex items-center gap-4 h-full"><div className={`p-3 rounded-lg ${color} shrink-0`}><Icon className="w-6 h-6 text-white" /></div><div><p className="text-sm text-slate-500 font-medium">{title}</p><p className="text-2xl font-bold text-slate-900">{value}</p></div></div>;
const pretty = (value: string) => value.replace(/_/g, ' ');

const Dashboard: React.FC = () => {
  const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const navigate = useNavigate();
  const load = async () => { try { setData(await complaintApi.dashboard()); } catch (e: any) { setError(e.response?.status === 403 ? 'MCC administrator access is required.' : 'Could not load live dashboard data.'); if (e.response?.status === 401 || e.response?.status === 403) navigate('/access/admin'); } };
  useEffect(() => { void load(); }, []);
  if (error) return <div className="max-w-xl mx-auto p-8 bg-white border rounded-xl"><h1 className="text-xl font-bold">MCC dashboard</h1><p className="mt-3 text-red-600">{error}</p></div>;
  const stats = data || { total: 0, verified: 0, needs_review: 0, not_resolved: 0, partial: 0, recurring: 0, recent: [] };
  const logout = () => { localStorage.removeItem('mcc_token'); localStorage.removeItem('mcc_user'); navigate('/'); };
  return <div className="space-y-8 max-w-[1600px] mx-auto"><div className="flex justify-between items-end"><div className="space-y-1"><h1 className="text-3xl font-bold text-slate-900 tracking-tight">Municipal Control Room</h1><p className="text-slate-500">Live complaint and AI-verification overview</p></div><div className="flex items-center gap-3"><button onClick={() => void load()} className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-xs font-semibold border border-blue-200">LIVE DATA · Refresh</button><button onClick={logout} className="text-sm font-medium text-slate-600 hover:text-red-600">Logout</button></div></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-4"><StatCard title="Total Complaints" value={stats.total} icon={LayoutDashboard} color="bg-slate-600" /><StatCard title="AI Verified" value={stats.verified} icon={CheckCircle} color="bg-green-500" /><StatCard title="Needs Review" value={stats.needs_review} icon={AlertCircle} color="bg-orange-500" /><StatCard title="Not Resolved" value={stats.not_resolved} icon={AlertCircle} color="bg-red-500" /><StatCard title="Partial Fixes" value={stats.partial} icon={Clock} color="bg-yellow-500" /><StatCard title="Recurring locations" value={stats.recurring} icon={TrendingUp} color="bg-purple-500" /></div><MysuruMap /><div className="grid grid-cols-1 lg:grid-cols-3 gap-8"><div className="lg:col-span-2 bg-white p-6 rounded-xl shadow-sm border border-slate-200"><h2 className="text-lg font-bold text-slate-900 flex items-center gap-2"><MapIcon className="w-5 h-5 text-slate-500" /> Assignment behavior</h2><p className="mt-4 text-slate-600">MCC draws one non-overlapping boundary per worker. A public complaint is assigned only when its submitted location falls inside a saved worker area; otherwise it remains unassigned for MCC review.</p></div><div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 h-[260px] flex flex-col"><h2 className="text-lg font-bold text-slate-900 mb-4">Recent AI verifications</h2><div className="space-y-3 overflow-y-auto pr-2">{stats.recent.map((item: any) => <div key={item.complaint_number} className="p-3 border rounded-lg flex justify-between items-center"><div><p className="font-bold text-sm">{item.complaint_number}</p><p className="text-xs text-slate-500 capitalize">{pretty(item.issue_type)}</p></div><div className="text-right"><p className="text-xs font-bold text-blue-600">Score: {Math.round(item.score)}</p><p className="text-[10px] uppercase text-slate-400">{pretty(item.result)}</p></div></div>)}{!stats.recent.length && <p className="text-sm text-slate-500">No completed AI reviews yet.</p>}</div></div></div></div>;
};
export default Dashboard;
