import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { complaintApi } from '../services/api';
import { Complaint } from '../types/complaint';

const WorkerPortal: React.FC = () => {
  const [items, setItems] = useState<Complaint[]>([]); const [files, setFiles] = useState<Record<number, File | null>>({}); const [busy, setBusy] = useState<number | null>(null);
  const navigate = useNavigate(); const user = JSON.parse(localStorage.getItem('mcc_user') || '{}');
  const load = async () => { try { setItems(await complaintApi.workerInbox()); } catch { navigate('/access/worker'); } };
  useEffect(() => { void load(); }, []);
  const upload = async (item: Complaint) => { const file = files[item.id]; if (!file) return; setBusy(item.id); try { await complaintApi.uploadEvidence(item.id, file, { type:'AFTER', timestamp:new Date().toISOString(), latitude:item.latitude, longitude:item.longitude }); alert('After photo submitted. AI analysis will run automatically.'); await load(); } catch (error:any) { alert(error.response?.data?.detail || 'Upload failed'); } finally { setBusy(null); } };
  const acknowledge = async (item: Complaint) => { setBusy(item.id); try { await complaintApi.acknowledge(item.id); await load(); } catch (error:any) { alert(error.response?.data?.detail || 'Could not acknowledge this complaint'); } finally { setBusy(null); } };
  return <div className="max-w-5xl mx-auto p-6 space-y-6"><header className="flex justify-between"><div><p className="text-orange-600 font-bold text-sm">WORKER PORTAL · {user.service_area || 'SERVICE AREA'}</p><h1 className="text-3xl font-bold">Assigned area complaints</h1></div><button onClick={() => {localStorage.clear();navigate('/')}} className="text-sm text-slate-600">Logout</button></header><p className="text-slate-600">Acknowledge an assignment when you start work. Upload an After photo when work is completed; Gemini then verifies the Before/After pair.</p><div className="space-y-4">{items.map(item => <article key={item.id} className="bg-white border rounded-xl p-5"><div className="flex justify-between gap-4"><div><b>{item.complaint_number}</b><p className="capitalize mt-1">{item.issue_type.replace('_',' ')} · {item.address}</p><p className="text-sm text-slate-500">{item.description}</p></div><Link to={`/worker/complaints/${item.id}`} className="text-blue-600 text-sm">View evidence</Link></div><div className="mt-4 flex flex-wrap gap-3 items-center">{!item.worker_acknowledged_at && <button disabled={busy === item.id} onClick={() => acknowledge(item)} className="bg-slate-800 text-white px-4 py-2 rounded font-bold disabled:opacity-50">{busy === item.id ? 'Saving…' : 'Acknowledge / start work'}</button>}<input type="file" accept="image/*" onChange={e => setFiles({...files,[item.id]:e.target.files?.[0] || null})}/><button disabled={!files[item.id] || busy === item.id} onClick={() => upload(item)} className="bg-orange-600 text-white px-4 py-2 rounded font-bold disabled:opacity-50">{busy === item.id ? 'Submitting…' : 'Upload After photo'}</button></div></article>)}{!items.length && <p className="text-slate-500">No complaints currently assigned to this area.</p>}</div></div>;
};
export default WorkerPortal;
